import 'package:meta/meta.dart';

/// How the merchant has configured the widget's availability surface.
///
/// Mirrors the `offline_mode` reported on the `site_config` payload.
/// The SDK consumes this
/// value to decide whether to show online/offline UX in v0.2.0 — for now
/// it is parsed and exposed for downstream code (and the headless demo)
/// to react to as it sees fit.
enum OfflineMode {
  /// Availability is derived from agent presence + business hours.
  auto,

  /// Merchant has explicitly marked the widget as offline.
  manualOffline,

  /// Merchant has explicitly forced the widget to look online.
  manualOnline,
}

OfflineMode _offlineModeFromString(String? raw) {
  switch (raw) {
    case 'manual_offline':
      return OfflineMode.manualOffline;
    case 'manual_online':
      return OfflineMode.manualOnline;
    case 'auto':
    default:
      return OfflineMode.auto;
  }
}

DateTime? _parseNextAvailable(Object? raw) {
  if (raw is! String) return null;
  final parsed = DateTime.tryParse(raw);
  return parsed?.toUtc();
}

/// Per-language overrides for the widget chrome and copy.
///
/// One variant per supported language is delivered under a [SiteConfig].
/// The customer's preferred language picks one variant — its
/// `welcomeMessage`, `headerTitle`, and offline copy take precedence over
/// the site-level fallbacks.
@immutable
class SiteLanguageVariant {
  /// Creates a [SiteLanguageVariant] with explicit fields.
  const SiteLanguageVariant({
    required this.languageCode,
    this.isDefault = false,
    this.isAutoGenerated = false,
    this.welcomeMessage,
    this.headerTitle,
    this.inputPlaceholder,
    this.offlineTitle,
    this.offlineSubtitle,
    this.emailLabel,
  });

  /// Parses a single variant entry from the `site:X` channel join payload.
  factory SiteLanguageVariant.fromJson(Map<String, dynamic> json) {
    return SiteLanguageVariant(
      languageCode: (json['language_code'] as String?) ?? '',
      isDefault: (json['is_default'] as bool?) ?? false,
      isAutoGenerated: (json['is_auto_generated'] as bool?) ?? false,
      welcomeMessage: json['welcome_message'] as String?,
      headerTitle: json['header_title'] as String?,
      inputPlaceholder: json['input_placeholder'] as String?,
      offlineTitle: json['offline_title'] as String?,
      offlineSubtitle: json['offline_subtitle'] as String?,
      emailLabel: json['email_label'] as String?,
    );
  }

  /// ISO language code this variant applies to (e.g. `pl`, `en`).
  final String languageCode;

  /// Whether this variant is the site's default — used as a fallback when
  /// the customer's preferred language has no matching variant.
  final bool isDefault;

  /// Whether the variant's copy was machine-translated rather than
  /// authored by the merchant.
  final bool isAutoGenerated;

  /// Welcome message shown as the first agent bubble for customers using
  /// this language. Falls back to [SiteConfig.siteWelcomeMessage] when null.
  final String? welcomeMessage;

  /// Title rendered in the chat header (e.g. `"Customer Support"`).
  final String? headerTitle;

  /// Placeholder text for the message composer.
  final String? inputPlaceholder;

  /// Title shown over the offline form (when v0.2.0 offline UX ships).
  final String? offlineTitle;

  /// Subtitle shown under [offlineTitle].
  final String? offlineSubtitle;

  /// Label for the e-mail field in the offline form.
  final String? emailLabel;

  @override
  bool operator ==(Object other) =>
      other is SiteLanguageVariant &&
      other.languageCode == languageCode &&
      other.isDefault == isDefault &&
      other.isAutoGenerated == isAutoGenerated &&
      other.welcomeMessage == welcomeMessage &&
      other.headerTitle == headerTitle &&
      other.inputPlaceholder == inputPlaceholder &&
      other.offlineTitle == offlineTitle &&
      other.offlineSubtitle == offlineSubtitle &&
      other.emailLabel == emailLabel;

  @override
  int get hashCode => Object.hash(
    languageCode,
    isDefault,
    isAutoGenerated,
    welcomeMessage,
    headerTitle,
    inputPlaceholder,
    offlineTitle,
    offlineSubtitle,
    emailLabel,
  );
}

/// Snapshot of the per-site configuration returned by the backend on the
/// `site:X` Phoenix channel join.
///
/// Surfaces the merchant-controlled chrome the SDK and merchant UIs render:
/// welcome message, header title, offline mode, language variants. Fields
/// the SDK does not yet model are preserved in [raw] for forward
/// compatibility — when the backend adds new keys, downstream code can
/// read them without waiting for a new SDK release.
@immutable
class SiteConfig {
  /// Creates a [SiteConfig] with explicit fields.
  const SiteConfig({
    this.widgetLanguage = 'en',
    this.siteWelcomeMessage,
    this.offlineMode = OfflineMode.auto,
    this.workingHoursEnabled = false,
    this.typingPreviewEnabled = false,
    this.autoTranslationsEnabled = false,
    this.widgetOpenOn = 'hover',
    this.nextAvailable,
    this.languageVariants = const [],
    this.raw = const {},
  });

  /// Parses the `site_config` map from the `site:X` channel join payload.
  factory SiteConfig.fromJson(Map<String, dynamic> json) {
    final variantsRaw = json['language_variants'];
    final variants = <SiteLanguageVariant>[];
    if (variantsRaw is List) {
      for (final entry in variantsRaw) {
        if (entry is Map) {
          variants.add(
            SiteLanguageVariant.fromJson(Map<String, dynamic>.from(entry)),
          );
        }
      }
    }
    return SiteConfig(
      widgetLanguage: (json['widget_language'] as String?) ?? 'en',
      siteWelcomeMessage: json['welcome_message'] as String?,
      offlineMode: _offlineModeFromString(json['offline_mode'] as String?),
      workingHoursEnabled: (json['working_hours_enabled'] as bool?) ?? false,
      typingPreviewEnabled: (json['typing_preview_enabled'] as bool?) ?? false,
      autoTranslationsEnabled:
          (json['auto_translations_enabled'] as bool?) ?? false,
      widgetOpenOn: (json['widget_open_on'] as String?) ?? 'hover',
      nextAvailable: _parseNextAvailable(json['next_available']),
      languageVariants: List<SiteLanguageVariant>.unmodifiable(variants),
      raw: Map<String, dynamic>.unmodifiable(json),
    );
  }

  /// Default language the widget renders in if the customer's preferred
  /// language has no matching variant.
  final String widgetLanguage;

  /// Site-level welcome message fallback. Used when the active language
  /// variant has no `welcome_message` of its own.
  final String? siteWelcomeMessage;

  /// How the widget's availability is determined.
  final OfflineMode offlineMode;

  /// Whether the backend enforces business hours for this site.
  final bool workingHoursEnabled;

  /// Whether agents see the customer's draft as they type.
  final bool typingPreviewEnabled;

  /// Whether server-side translation between agent and customer is on.
  final bool autoTranslationsEnabled;

  /// Whether the web widget auto-opens on hover or only on click. Not
  /// consumed by the Flutter SDK (which mounts via navigation), kept for
  /// merchants who share configuration across surfaces.
  final String widgetOpenOn;

  /// Estimated wall-clock instant when the next agent becomes available,
  /// as reported by the backend (typically while [workingHoursEnabled] is
  /// `true` and the current moment falls outside the configured window).
  ///
  /// Always in UTC when present. Always `null` when the backend has not
  /// computed or chosen to expose this value — consumers must treat it as
  /// best-effort UX hint, not as a guarantee.
  final DateTime? nextAvailable;

  /// All per-language variants the merchant has configured, in arrival
  /// order.
  final List<SiteLanguageVariant> languageVariants;

  /// The full server payload, unmodifiable. Preserved so backend additions
  /// remain reachable from custom UI before the SDK models them.
  final Map<String, dynamic> raw;

  /// Returns the variant matching [languageCode], or the variant marked
  /// `is_default: true`, or `null` if neither is present.
  SiteLanguageVariant? variantFor(String? languageCode) {
    if (languageVariants.isEmpty) return null;
    if (languageCode != null) {
      for (final v in languageVariants) {
        if (v.languageCode == languageCode) return v;
      }
    }
    for (final v in languageVariants) {
      if (v.isDefault) return v;
    }
    return null;
  }

  /// Resolves the welcome message to render for a customer speaking
  /// [languageCode]: variant-level override first, site-level fallback
  /// second, `null` when nothing is configured.
  String? activeWelcomeMessage(String? languageCode) {
    final variant = variantFor(languageCode);
    return variant?.welcomeMessage ?? siteWelcomeMessage;
  }

  /// Resolves the header title (e.g. `"Customer Support"`) for a customer
  /// speaking [languageCode]. Returns `null` if no variant supplies one.
  String? activeHeaderTitle(String? languageCode) =>
      variantFor(languageCode)?.headerTitle;

  @override
  bool operator ==(Object other) =>
      other is SiteConfig &&
      other.widgetLanguage == widgetLanguage &&
      other.siteWelcomeMessage == siteWelcomeMessage &&
      other.offlineMode == offlineMode &&
      other.workingHoursEnabled == workingHoursEnabled &&
      other.typingPreviewEnabled == typingPreviewEnabled &&
      other.autoTranslationsEnabled == autoTranslationsEnabled &&
      other.widgetOpenOn == widgetOpenOn &&
      other.nextAvailable == nextAvailable &&
      _listEquals(other.languageVariants, languageVariants);

  @override
  int get hashCode => Object.hash(
    widgetLanguage,
    siteWelcomeMessage,
    offlineMode,
    workingHoursEnabled,
    typingPreviewEnabled,
    autoTranslationsEnabled,
    widgetOpenOn,
    nextAvailable,
    Object.hashAll(languageVariants),
  );
}

bool _listEquals<T>(List<T> a, List<T> b) {
  if (a.length != b.length) return false;
  for (var i = 0; i < a.length; i++) {
    if (a[i] != b[i]) return false;
  }
  return true;
}
