name: Examples build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze:
    name: Analyze examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: any
          channel: stable
          cache: true
      - name: Pub get
        working-directory: examples/quickstart
        run: flutter pub get
      - name: Analyze
        working-directory: examples/quickstart
        run: flutter analyze
